export const Images = {
  dummyImage: require('./dummyProfileImage.png'),
  profileImage: require('./profile.png'),
  pushupImage: require('./pushups.png'),
  runningImage: require('./running.png'),
  BiscepsImage: require('./Bisceps.png'),
  DumbbellDeltRow: require('./DumbbellDeltRow.png'),
  DumbbellDeltLarge: require('./Rectangle.png'),
  barbell: require('./barbell.png'),
  chainUp: require('./chainUp.png'),
  deadLift: require('./deadLift.png'),
  dumbbell: require('./dumbbell.png'),
  kettlebell: require('./kettlebell.png'),
  homeIcon: require('./homeIcon.png'),
  programIcon: require('./programIcon.png'),
  addIcon: require('./addIcon.png'),
  messageIcon: require('./message.png'),
  menuIcon: require('./menuIcon.png'),
  galleryIcon: require('./iconGallery.png'),
  cameraIcon: require('./camera.png'),
  dot: require('./dot.png'),
  bottomedge: require('./Polygon.png'),
  exerciseImage: require('./exercise.png'),
  videoUpload: require('./videoUpload.png'),
  profileIcon: require('./profileIcon.png'),
  googleIcon: require('./google.png'),
  facebookIcon: require('./facebook.png'),
  appleIcon: require('./apple.png'),
  eyeIcon: require('./eye1.png'),
  logoIcon: require('./icon.png'),
  splashIcon: require('./splash-logo.png'),
  eyeHideIcon: require('./eyehide.png'),
  duplicateIcon: require('./duplicate.png'),
  archiveIcon: require('./archive.png'),
  folderIcon: require('./folder.png'),
  settingIcon:require('./settings.png'),

};
